name: 'make_packages'
description: 'make_packages'
inputs:
  container-id:  # id of input
    description: 'The running container id'
    required: true
  os:
    description: 'The system of container'
    required: true
  version:
    description: 'The version of packages'
    required: true
  cpu_num:
    description: 'The cpu_num of machine'
    required: true
runs:
  using: "composite"
  steps:
  - id: make-packages
    run: |
      docker exec ${{ inputs.container-id }} bash -c 'cd /root && source /etc/profile;
          cp -r inclavare-containers inclavare-containers-${{ inputs.version }};
          tar zcf v${{ inputs.version }}.tar.gz inclavare-containers-${{ inputs.version }};
          mkdir -p /root/inclavare-containers/${{ matrix.tag }}'

      if [ '${{ inputs.os }}' = 'ubuntu18.04' ]; then
        docker exec ${{ inputs.container-id }} bash -c "cd inclavare-containers-${{ inputs.version }};
          find ./ -path '*deb/build.sh' | xargs -I files sed -i '17 d' files;
          find ./ -path '*deb/build.sh' | xargs -I files sed -i '17icp /root/v*.tar.gz \$DEBBUILD_DIR' files;
          sed -i 's/shelter//g' Makefile;
          sed -i 's/inclavared//g' Makefile;
          make package -j${{ inputs.cpu_num }};
          mv *.deb /root/inclavare-containers/${{ inputs.os }}"
      else
        docker exec ${{ inputs.container-id }} bash -c "cd inclavare-containers-${{ inputs.version }};
          mkdir -p /root/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS};
          cp -f /root/v$RUNE_VERSION.tar.gz /root/rpmbuild/SOURCES;
          find ./ -path '*dist/Makefile' | xargs -I files sed -i '16 d' files;
          sed -i 's/shelter//g' Makefile;
          sed -i 's/inclavared//g' Makefile;
          make package RPMBUILD_DIR=/root/rpmbuild -j${{ inputs.cpu_num }};
          mv *.rpm /root/inclavare-containers/${{ inputs.os }}"
      fi
    shell: bash
