name: pull_request

on:
  pull_request:
    types: [synchronize, reopened, labeled]
    branches:
      - master
      - 'v[0-9]+.*'

defaults:
  run:
    shell: bash

jobs:
  lint:
    name: cpplint
    if: ${{ contains(github.event.pull_request.labels.*.name, 'start-testing') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Cpplint
        run: |
          echo "Hello!!!!" 
