name: Inclavare Containers CI

# Controls when the action will run. Triggers the workflow on push or pull request
#on: [push, pull_request]
on: [workflow_dispatch]

env:
  occlum_version: 0.17.0
  nap_time: 60

jobs:
  rune_crictl-centos:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
      with:
       submodules: true

    - name: Create container
      run: docker run -itd --privileged --name=crictl-centos --net host --device /dev/isgx -v /var/run/aesmd:/var/run/aesmd -v $GITHUB_WORKSPACE:/root/inclavare-containers centos-crictl-success:v2

    - name: Build and install rune
      run: docker exec crictl-centos bash -c "cd /root;
            cp -r inclavare-containers inclavare-containers-0.5.0;
            tar zcf v0.5.0.tar.gz inclavare-containers-0.5.0;
            source /etc/profile && cd /root/inclavare-containers-0.5.0;
            mkdir -p /root/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS};
            cp /root/v0.5.0.tar.gz /root/rpmbuild/SOURCES/;
            sed -i '16 d' /root/inclavare-containers-0.5.0/rune/dist/Makefile;
            source /etc/profile; make package components=rune RPMBUILD_DIR=/root/rpmbuild RELEASE_TARBALL_FILE=/root/rpmbuild/SOURCES/v0.5.0.tar.gz RELEASE_TARBALL_EXIST=y;
            make package components=shim RPMBUILD_DIR=/root/rpmbuild RELEASE_TARBALL_FILE=/root/rpmbuild/SOURCES/v0.5.0.tar.gz RELEASE_TARBALL_EXIST=y;
            rpm -ivh rune-0.5.0-1.el8.x86_64.rpm;
            rpm -ivh shim-rune-0.5.0-1.el8.x86_64.rpm;"

    - name: occlum-hello pod
      run: docker exec crictl-centos bash -c "containerd" & 
           docker exec crictl-centos bash -c "cd /root/samples && ./clean.sh;
            crictl run --timeout 1s hello.yaml pod.yaml && ./show.sh"

    - name: Kill the container
      run: |
        sleep ${{ env.nap_time }};
        docker stop crictl-centos
