name: Set up Package Repository and Test (Manual Trigger)

# This is a manual trigger.
on: [workflow_dispatch]

jobs:
  Test_deb_package:
    runs-on: [self-hosted, ubuntu]
    steps:
    - name: Create a clean ubuntu container
      run: docker run -itd --name=ubuntu ubuntu:18.04

    - name: Configure repo
      run: |
          docker exec ubuntu bash -c "apt-get update && apt-get install -y gnupg wget;
          echo 'deb [arch=amd64] https://mirrors.openanolis.org/inclavare-containers/deb-repo bionic main' | tee /etc/apt/sources.list.d/inclavare-containers.list;
          wget -qO - https://mirrors.openanolis.org/inclavare-containers/deb-repo/DEB-GPG-KEY.key  | apt-key add -;

          cat <<- EOF >/etc/apt/preferences.d/inclavare-containers
          Package: epm
          Pin: origin mirrors.openanolis.org
          Pin-Priority: 1000
          EOF"

    - name: Install rune
      run: docker exec ubuntu bash -c "apt-get update; apt-get install -y rune"

    - name: Stop the container
      run: docker stop ubuntu

  Test_rpm_package:
    runs-on: [self-hosted, ubuntu]
    steps:
    - name: Create clean centos container
      run: docker run -itd --name=centos centos:centos8.1.1911

    - name: Install package
      run: |
        docker exec centos bash -c "cat << EOF >/etc/yum.repos.d/inclavare-containers.repo
        [inclavare-containers]
        name=inclavare-containers
        enabled=1
        baseurl=https://mirrors.openanolis.org/inclavare-containers/rpm-repo/
        gpgcheck=1
        repo_gpgcheck=1
        gpgkey=https://mirrors.openanolis.org/inclavare-containers/rpm-repo/RPM-GPG-KEY-rpm-sign
        gpgcakey=https://mirrors.openanolis.org/inclavare-containers/rpm-repo/RPM-GPG-KEY-rpm-sign-ca
        EOF"

        docker exec centos bash -c "yum --showduplicate list -y rune; yum install -y rune"
    - name: Stop the docker
      run: docker stop centos
